### ISSUE TITLE
Still not running on IE or Edge

### ISSUE THREAD

**Issue by DickChesterwood** [DickChesterwood/k8s-fleetman#25]
Edge doesn't even "see" the ip address of docker-machine

**Comment by DickChesterwood** [comment]
IE11: rebuilding with prod mode off, we can now see errors in the console:

"Error: SyntaxError
   at callWithDebugContext (http://192.168.99.100/vendor.bundle.js:60293:9)
   at debugCreateRootView (http://192.168.99.100/vendor.bundle.js:59566:5)
   at ComponentFactory_.prototype.create (http://192.168.99.100/vendor.bundle.js:56463:9)
   at ComponentFactoryBoundToModule.prototype.create (http://192.168.99.100/vendor.bundle.js:49215:9)
   at ApplicationRef.prototype.bootstrap (http://192.168.99.100/vendor.bundle.js:51050:9)
   at Anonymous function (http://192.168.99.100/vendor.bundle.js:50777:67)
   at PlatformRef.prototype._moduleDoBootstrap (http://192.168.99.100/vendor.bundle.js:50777:13)
   at Anonymous function (http://192.168.99.100/vendor.bundle.js:50698:21)
   at ZoneDelegate.prototype.invoke (http://192.168.99.100/polyfills.bundle.js:6159:13)
   at onInvoke (http://192.168.99.100/vendor.bundle.js:49945:17)"

**Comment by DickChesterwood** [comment]
Perhaps more useful:

 SCRIPT5011: Can't execute code from a freed script polyfills.bundle.js

**Comment by DickChesterwood** [comment]
Going to try an upgrade to the latest Angular, it may be caused by out of date packages or something.

**Comment by DickChesterwood** [comment]
Total failure. Still the same problem. Think the freed script thing is a red herring....

**Comment by DickChesterwood** [comment]
I really don't have time for this. I'm going to have to cut losses and declare no support for IE11.

The edge problem is very weird, it isn't resolving local network addresses.

**Comment by duvangil** [comment]
hello @DickChesterwood  i have the same error in my project, And I don't know how to fix it, did you find anything ?  
![image](https://user-images.githubusercontent.com/17736493/63039501-11351800-be89-11e9-80c9-27b88ad6fe91.png)

**Comment by RichardKnowles** [comment]
Hi, sorry I didn't ever get to the root of this - is it working for you in chrome or firefox?

I assumed I would get lots of complaints about this from the course, but I haven't heard anything about it so far.
